Explicitly state max_connections and timeout defaults in docs
benoitc/hackney pull request #688
Opened 2021-06-10 12:35 UTC by sbinlondon

There's no explicitly stated defaults (that I can find) for `max_connections` and `timeout`.

The README examples, if they are examples of the defaults, say `100` for `max_connections` but then [in `hackney.app.src` it seems to be `50`](https://github.com/benoitc/hackney/blob/01bb4249f595e0aa692db28ef23e70f57ae2d4ed/src/hackney.app.src#L25)? I went with that one but if it is something else, please let me know and happy to update my PR.

Either way it would be helpful to have very clearly stated defaults.

2021-06-17 09:43 UTC, benoitc requested changes
thanks for the changes, this is very helpful. Can you add also the unit to the timeout ?

2021-06-17 09:43 UTC, benoitc commented on README.md
> +automatically. The default timeout is `150000` and the default number of connections is `50`.
Can you add the unit to the timeout? ie.   150000 ms  sot it would definitely clarify the text

2021-06-29 09:56 UTC, sbinlondon commented
@benoitc let me know if that new formatting is ok or if you want any more changes.

2023-10-10 00:13 UTC, merged

2023-10-10 00:13 UTC, benoitc commented
finally merged. Thanks!